db:
  driver: ${DB_DRIVER}
  host: ${DB_HOST}
  port: ${DB_PORT}
  user: ${DB_USER}
  password: ${DB_PASS}
  name: ${DB_NAME}
handler:
  path: ./handlers
  prefix: /api
  versions:
    v1:
      prefix: /v1
      routes:
        article:
          prefix: /articles
          actions:
            create: 
              method: POST
              path: /
              handler: Create
            get:
              method: GET
              path: /:id
              handler: Get
            update:
              method: PUT
              path: /:id
              handler: Update
            delete:
              method: DELETE
              path: /:id
              handler: Delete
          user:
            prefix: /users
            create:
              method: POST
              path: /users
              handler: Create
    v2:
      prefix: /v2
      routes:
        article:
          prefix: /articles
          actions:
            create: 
              method: POST
              path: /
              handler: Create