version: "3.8"

services:
  zitadel:
    restart: "always"
    networks:
      - "zitadel"
    image: "ghcr.io/zitadel/zitadel:latest"
    command: 'start-from-init --config  /zitadel-config.yaml --steps /zitadel-init-steps.yaml --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    environment:
      - "ZITADEL_DATABASE_COCKROACH_HOST=crdb"
      - "ZITADEL_EXTERNALSECURE=false"
      - "ZITADEL_LOG_LEVEL=info"
      - "ZITADEL_DEFAULTINSTANCE_ORG_NAME=OnTheGo"
      - ZITADEL_DEFAULTINSTANCE_CUSTOMDOMAIN=localhost
      - ZITADEL_DEFAULTINSTANCE_DOMAINPOLICY_SMTPSENDERADDRESSMATCHESINSTANCEDOMAIN=false
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_HOST=smtp.gmail.com:465
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_USER=vietanh12a4@gmail.com
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_PASSWORD=qgqtrnyscarsmvji
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_TLS=true
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_FROM=support.trinhvietanh.net
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_FROMNAME=support.trinhvietanh.net
      # - "ZITADEL_DEFAULTINSTANCE_ORG_MACHINE_MACHINE_USERNAME=core_service_user"
      # - "ZITADEL_DEFAULTINSTANCE_ORG_MACHINE_MACHINE_NAME=core_service_user"
      # - 'ZITADEL_DEFAULTINSTANCE_ORG_HUMAN_USERNAME=root'
      # - 'ZITADEL_DEFAULTINSTANCE_ORG_HUMAN_PASSWORD=Password1!'
      # - "ZITADEL_FIRSTINSTANCE_MACHINEKEYPATH=/machinekey/core_service_user_key.json"
      # - "ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINEKEY_TYPE=1"
    depends_on:
      crdb:
        condition: "service_healthy"
    ports:
      - "8080:8080"
    volumes:
      - "./zitadel-init-steps.yaml:/zitadel-init-steps.yaml"
      - ./machinekey:/machinekey
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro

  crdb:
    restart: "always"
    networks:
      - "zitadel"
    image: "cockroachdb/cockroach:v22.2.2"
    command: "start-single-node --insecure"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: "10s"
      timeout: "30s"
      retries: 5
      start_period: "20s"
    ports:
      - "9090:8080"
      - "26257:26257"

networks:
  zitadel:
