version: "3.8"

services:
  crdb:
    restart: "always"
    networks:
      - "onthego"
    image: "cockroachdb/cockroach:v22.2.2"
    command: "start-single-node --insecure"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: "10s"
      timeout: "30s"
      retries: 5
      start_period: "20s"
    ports:
      - "9090:8080"
      - "26257:26257"

  zitadel:
    restart: "always"
    networks:
      - "onthego"
    image: "ghcr.io/zitadel/zitadel:latest"
    command: 'start-from-init --config  /zitadel-config.yaml --steps /zitadel-init-steps.yaml --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/debug/healthz"]
      interval: "10s"
      timeout: "30s"
      retries: 5
      start_period: "20s"
    environment:
      - "ZITADEL_DATABASE_COCKROACH_HOST=crdb"
      - "ZITADEL_EXTERNALSECURE=false"
      - "ZITADEL_LOG_LEVEL=info"
      - "ZITADEL_DEFAULTINSTANCE_ORG_NAME=OnTheGo"
      - ZITADEL_DEFAULTINSTANCE_DOMAINPOLICY_SMTPSENDERADDRESSMATCHESINSTANCEDOMAIN=false
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_HOST=smtp.gmail.com:465
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_USER=vietanh12a4@gmail.com
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_PASSWORD=qgqtrnyscarsmvji
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_TLS=true
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_FROM=support.trinhvietanh.net
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_FROMNAME=support.trinhvietanh.net
    depends_on:
      crdb:
        condition: "service_healthy"
    ports:
      - "8080:8080"
    volumes:
      - "./zitadel-init-steps.yaml:/zitadel-init-steps.yaml"
      - ./machinekey:/machinekey
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro

  onthego:
    restart: "always"
    environment:
      - ENV=LOCAL
      - PORT=9000
      - SSL=FALSE
      - API_VERSION=1.0
      - DB_DRIVER=postgres
      - DB_USER=root
      - DB_PASS=postgres
      - DB_HOST=host.docker.internal
      - DB_PORT=26257
      - DB_NAME=onthego
      - REDIS_SECRET=hjfhjhasdfkyuy2
      - REDIS_HOST=127.0.0.1:6379
      - REDIS_PASSWORD=
      - ZITADEL_USER_EMAIL=vietanh8i1998@gmail.com
      - ZITADEL_USERNAME=core_human_user
      - ZITADEL_PASSWORD=CoreHumanPassword1!
      - ZITADEL_DOMAIN=http://host.docker.internal:8080
      - API_DOMAIN=http://host.docker.internal:9000
      - FILE_UPLOAD_PATH=uploads
      - UPLOAD_DRIVER=local
      - SIGNED_URL_SECRET=CatMeowMeow123
      - ZITADEL_DATABASE_COCKROACH_HOST=crdb
      - ZITADEL_EXTERNALSECURE=false
      - ZITADEL_LOG_LEVEL=info
      - ZITADEL_DEFAULTINSTANCE_ORG_NAME=OnTheGo
      - ZITADEL_DEFAULTINSTANCE_DOMAINPOLICY_SMTPSENDERADDRESSMATCHESINSTANCEDOMAIN=false
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_HOST=smtp.gmail.com:465
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_USER=vietanh12a4@gmail.com
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_PASSWORD=qgqtrnyscarsmvji
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_TLS=true
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_FROM=support.trinhvietanh.net
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_FROMNAME=support.trinhvietanh.net
    networks:
      - "onthego"
    image: "auditt98/onthego:main"
    depends_on:
      crdb:
        condition: service_healthy
      zitadel:
        condition: service_completed_successfully
    ports:
      - "9000:9000"
    volumes:
      - "./zitadel-init-steps.yaml:/zitadel-init-steps.yaml"
      - "./machinekey:/machinekey"

networks:
  onthego:
