version: "3.8"

services:
  crdb:
    restart: "always"
    networks:
      - "onthego"
    image: "cockroachdb/cockroach:v22.2.2"
    command: "start-single-node --insecure"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: "10s"
      timeout: "30s"
      retries: 15
      start_period: "20s"
    ports:
      - "9090:8080"
      - "26257:26257"
    volumes:
      - "./zitadel-init-steps.yaml:/zitadel-init-steps.yaml"
      - ./machinekey:/machinekey

  zitadel:
    restart: "always"
    networks:
      - "onthego"
    image: "ghcr.io/zitadel/zitadel:latest"
    tty: true
    command: 'start-from-init --steps /zitadel-init-steps.yaml --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    environment:
      - ZITADEL_DATABASE_COCKROACH_HOST=crdb
      - "ZITADEL_EXTERNALSECURE=false"
      - "ZITADEL_LOG_LEVEL=info"
      - "ZITADEL_DEFAULTINSTANCE_ORG_NAME=OnTheGo"
      - ZITADEL_DEFAULTINSTANCE_DOMAINPOLICY_SMTPSENDERADDRESSMATCHESINSTANCEDOMAIN=false
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_HOST=smtp.gmail.com:465
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_USER=vietanh12a4@gmail.com
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_PASSWORD=qgqtrnyscarsmvji
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_TLS=true
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_FROM=support.trinhvietanh.net
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_FROMNAME=support.trinhvietanh.net
      - ZITADEL_LOGSTORE_ACCESS_STDOUT_ENABLED=true
      - ZITADEL_LOGSTORE_EXECUTION_DATABASE_ENABLED=true
      - ZITADEL_FIRSTINSTANCE_MACHINEKEYPATH=/machinekey/core_service_user_key.json
      - ZITADEL_FIRSTINSTANCE_INSTANCENAME=OnTheGo
      - ZITADEL_FIRSTINSTANCE_ORG_NAME=OnTheGo
      - ZITADEL_FIRSTINSTANCE_ORG_MACHINE_USERNAME=core_service_user
      - ZITADEL_FIRSTINSTANCE_ORG_MACHINE_NAME=core_service_user
      - ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINEKEY_TYPE=1
    depends_on:
      crdb:
        condition: "service_healthy"
    ports:
      - "8080:8080"
    volumes:
      - "./zitadel-init-steps.yaml:/zitadel-init-steps.yaml"
      - ./machinekey:/machinekey
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro

  # onthego:
  #   restart: "always"
  #   environment:
  #     - ENV=LOCAL
  #     - PORT=9000
  #     - SSL=FALSE
  #     - API_VERSION=1.0
  #     - DB_DRIVER=postgres
  #     - DB_USER=root
  #     - DB_PASS=postgres
  #     - DB_HOST=localhost
  #     - DB_PORT=26257
  #     - DB_NAME=onthego
  #     - REDIS_SECRET=hjfhjhasdfkyuy2
  #     - REDIS_HOST=127.0.0.1:6379
  #     - REDIS_PASSWORD=
  #     - ZITADEL_USER_EMAIL=vietanh8i1998@gmail.com
  #     - ZITADEL_USERNAME=core_human_user
  #     - ZITADEL_PASSWORD=CoreHumanPassword1!
  #     - ZITADEL_DOMAIN=http://localhost:8080
  #     - API_DOMAIN=http://localhost:9000
  #     - FILE_UPLOAD_PATH=uploads
  #     - UPLOAD_DRIVER=local
  #     - SIGNED_URL_SECRET=CatMeowMeow123
  #     - ZITADEL_DATABASE_COCKROACH_HOST=http://localhost:26257
  #     - ZITADEL_EXTERNALSECURE=false
  #     - ZITADEL_LOG_LEVEL=info
  #     - ZITADEL_DEFAULTINSTANCE_ORG_NAME=OnTheGo
  #     - ZITADEL_DEFAULTINSTANCE_DOMAINPOLICY_SMTPSENDERADDRESSMATCHESINSTANCEDOMAIN=false
  #     - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_HOST=smtp.gmail.com:465
  #     - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_USER=vietanh12a4@gmail.com
  #     - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_PASSWORD=qgqtrnyscarsmvji
  #     - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_TLS=true
  #     - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_FROM=support.trinhvietanh.net
  #     - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_FROMNAME=support.trinhvietanh.net
  #     - DEFAULT_CLIENT_ID_PATH=/machinekey/default_client_id.txt
  #     - DEFAULT_API_SECRET_PATH=/machinekey/default_api_secret.json
  #     - DEFAULT_API_INTROSPECTION_SECRET_PATH=/machinekey/default_api_introspection_secret.json
  #     - DEFAULT_SU_KEY_PATH=/machinekey/core_service_user_key.json
  #   networks:
  #     - "onthego"
  #   image: "auditt98/onthego:main"
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - "./zitadel-init-steps.yaml:/zitadel-init-steps.yaml"
  #     - "./machinekey:/machinekey"
  #   command: /bin/bash -c "until [ \"\$(curl -s -o /dev/null -w ''%{http_code}'' http://host.docker.internal:8080/debug/ready)\" == \"200\" ]; do echo 'Waiting for service to be ready...'; sleep 5; done && sleep 20 && ./main"

networks:
  onthego:
