---
apiVersion: apps/v1
kind: Deployment # Type of Kubernetes resource
metadata:
  name: onthego-deployment # Name of the Kubernetes resource
spec:
  replicas: 3 # Number of pods to run at any given time
  selector:
    matchLabels:
      app: onthego-deployment # This deployment applies to any Pods matching the specified label
  template: # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels: # The labels that will be applied to all of the pods in this deployment
        app: onthego-deployment
    spec: # Spec for the container which will run in the Pod
      containers:
        - name: onthego-deployment
          image: auditt98/onthego:main
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000 # Should match the port number that the Go application listens on
          # livenessProbe: # To check the health of the Pod
          #   httpGet:
          #     path: /rk/v1/alive
          #     port: 9000
          #     scheme: HTTP
          #   initialDelaySeconds: 5
          #   periodSeconds: 15
          #   timeoutSeconds: 5
          # readinessProbe: # To check if the Pod is ready to serve traffic or not
          #   httpGet:
          #     path: /rk/v1/ready
          #     port: 9000
          #     scheme: HTTP
          #   initialDelaySeconds: 5
          #   timeoutSeconds: 1
