version: "3.8"

services:
  crdb:
    restart: "always"
    networks:
      - "zitadel"
    image: "cockroachdb/cockroach:v22.2.2"
    command: "start-single-node --insecure"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: "10s"
      timeout: "30s"
      retries: 15
      start_period: "20s"
    ports:
      - "9090:8080"
      - "26257:26257"

  zitadel:
    restart: "always"
    networks:
      - "zitadel"
    image: "ghcr.io/zitadel/zitadel:latest"
    command: 'start-from-init --masterkey "randomMasterKeyForSurehahahIsThis32Charactersyet" --tlsMode external'
    environment:
      - ZITADEL_DATABASE_COCKROACH_HOST=crdb
      - ZITADEL_EXTERNALSECURE=true
      - ZITADEL_EXTERNALPORT=443
      - ZITADEL_EXTERNALDOMAIN=zitadel.trinhvietanh.net
      - ZITADEL_LOG_LEVEL=info
      - ZITADEL_DEFAULTINSTANCE_ORG_NAME=OnTheGo
      - ZITADEL_DEFAULTINSTANCE_DOMAINPOLICY_SMTPSENDERADDRESSMATCHESINSTANCEDOMAIN=false
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_HOST=smtp.gmail.com:465
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_USER=vietanh12a4@gmail.com
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_PASSWORD=qgqtrnyscarsmvji
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_TLS=true
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_FROM=support.trinhvietanh.net
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_FROMNAME=support.trinhvietanh.net
      - ZITADEL_FIRSTINSTANCE_MACHINEKEYPATH=/machinekey/core_service_user_key.json
      - ZITADEL_FIRSTINSTANCE_ORG_MACHINE_USERNAME=core_service_user
      - ZITADEL_FIRSTINSTANCE_ORG_MACHINE_NAME=core_service_user
      - ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINEKEY_TYPE=1
    depends_on:
      crdb:
        condition: "service_healthy"
    ports:
      - "8080:8080"
    volumes:
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro

  onthego:
    restart: "always"
    environment:
      - ENV=LOCAL
      - PORT=9000
      - SSL=FALSE
      - API_VERSION=1.0
      - DB_DRIVER=postgres
      - DB_USER=root
      - DB_PASS=postgres
      - DB_HOST=crdb
      - DB_PORT=26257
      - DB_NAME=onthego
      - REDIS_SECRET=hjfhjhasdfkyuy2
      - REDIS_HOST=127.0.0.1:6379
      - REDIS_PASSWORD=
    networks:
      - "zitadel"
    image: "auditt98/onthego:main"
    ports:
      - "9000:9000"
    volumes:
      - "./zitadel-init-steps.yaml:/zitadel-init-steps.yaml"
      - "./machinekey:/machinekey"
    # command: /bin/bash -c "until [ \"\$(curl -s -o /dev/null -w ''%{http_code}'' http://host.docker.internal:8080/debug/ready)\" == \"200\" ]; do echo 'Waiting for service to be ready...'; sleep 5; done && sleep 20 && ./main"

networks:
  zitadel:
